name: CI with Athina Evals

on:
  push:
    branches:
      - main  # Trigger CI on pushes to main branch only

jobs:
  evaluate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install project dependencies
          pip install athina  # Install Athina Evals

      - name: Prepare Dataset
        run: |
          # If your dataset is not static, prepare it here
          # For example, download the dataset or build it from available data
          echo "Prepare your dataset here if necessary"
        
      - name: Run Athina Evaluation and Validation Script
        run: python -m evaluations.run_athina_evals
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
